<a href="https://colab.research.google.com/github/Dhanushgowda2342/AIML-journey/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/housing-prices-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'housing-prices-dataset' dataset.
Path to dataset files: /kaggle/input/housing-prices-dataset

In [77]:
import pandas as pd
import os

In [78]:
print(os.listdir(path))

['Housing.csv']

In [79]:
df = pd.read_csv(path+"/Housing.csv")

In [80]:
df.head(5)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [81]:
df.shape

(545, 13)

In [82]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [83]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [84]:
df.duplicated().sum()

np.int64(0)

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [92]:
bool_columns = ['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea']

for col in bool_columns:
    if df[col].dtype == 'object':   # only clean if string
        df[col] = df[col].str.strip().str.lower()
        df[col] = df[col].map({'yes':1, 'no':0})
df = df.drop('furnishingstatus', axis=1)

In [93]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea
0,13300000,7420,4,2,3,1,0,0,0,1,2,1
1,12250000,8960,4,4,4,1,0,0,0,1,3,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1
4,11410000,7420,4,1,2,1,1,1,0,1,2,0

In [94]:
y=df['price']
X=df.drop(['price'],axis=1)

In [95]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [96]:
df=df.dropna()

In [97]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [98]:
y_pred = model.predict(X_test)

In [99]:
import pandas as pd

result = pd.DataFrame({
    'Actual': y_test,
    'Predicted': y_pred
})

print(result.head(10))

      Actual     Predicted
316  4060000  5.398919e+06
77   6650000  7.065404e+06
360  3710000  2.993804e+06
90   6440000  4.535814e+06
493  2800000  3.053270e+06
209  4900000  3.709351e+06
176  5250000  5.440532e+06
249  4543000  6.228231e+06
516  2450000  2.882007e+06
426  3353000  2.341077e+06

In [100]:
new_house = [[3000, 3, 2, 2, 1, 0, 1, 0, 1, 2, 1]]
prediction = model.predict(new_house)

print("Predicted Price:", prediction)

Predicted Price: [6736398.95473621]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [101]:
from sklearn.metrics import r2_score

print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.6437296086614116

In [102]:
print(X.columns)
print(model.coef_)

Index(['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom',
       'basement', 'hotwaterheating', 'airconditioning', 'parking',
       'prefarea'],
      dtype='object')
[2.37710510e+02 7.84836476e+04 1.10932614e+06 4.26909551e+05
 4.12677757e+05 2.43606446e+05 4.35005497e+05 7.12264653e+05
 8.08415428e+05 2.47443135e+05 6.36787694e+05]